export const TECH_JOB_TITLE_OPTIONS = [
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Software Engineer',
  'Software Developer',
  'Web Developer',
  'Mobile App Developer',
  'Android Developer',
  'iOS Developer',
  'Cross-Platform Developer',
  'React Developer',
  'Vue Developer',
  'Angular Developer',
  'Node.js Developer',
  'PHP Developer',
  'Laravel Developer',
  'Python Developer',
  'Java Developer',
  'Spring Boot Developer',
  '.NET Developer',
  'C# Developer',
  'C++ Developer',
  'Go Developer',
  'Rust Developer',
  'Ruby on Rails Developer',
  'WordPress Developer',
  'Shopify Developer',
  'Game Developer',
  'Blockchain Developer',
  'Smart Contract Developer',
  'AR/VR Developer',
  'QA Engineer',
  'Automation Tester',
  'Manual QA Tester',
  'Performance Tester',
  'Security Engineer',
  'Cybersecurity Analyst',
  'SOC Analyst',
  'Penetration Tester',
  'Cloud Engineer',
  'Cloud Architect',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Platform Engineer',
  'Systems Administrator',
  'Network Engineer',
  'Database Administrator',
  'Data Engineer',
  'Data Analyst',
  'Business Intelligence Analyst',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'Prompt Engineer',
  'MLOps Engineer',
  'Product Manager',
  'Technical Product Manager',
  'Project Manager',
  'Scrum Master',
  'Business Analyst',
  'Solutions Architect',
  'Enterprise Architect',
  'UI Designer',
  'UX Designer',
  'UI/UX Designer',
  'Product Designer',
  'Graphic Designer',
  'Technical Support Engineer',
  'IT Support Specialist',
  'Help Desk Technician',
  'IT Officer',
  'ERP Specialist',
  'SAP Consultant',
  'Salesforce Developer',
  'Salesforce Administrator',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'IoT Engineer',
  'Robotics Engineer',
  'Computer Vision Engineer',
  'GIS Developer',
  'Tech Lead',
  'Engineering Manager',
  'Chief Technology Officer',
  'Other',
];



